name: Build (Linux)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev
    - name: Setup premake
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"
    - name: Run premake
      run: ./scripts/setupMake.sh
    - name: Compile
      run: make config=release verbose=true
