name: Build (Linux)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup premake
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"
    - name: Run premake
      run: ./scripts/setupMake.sh
    - name: Compile
      run: make config=Release -j8
